"""Forward-error-correction algorithms and bounded candidate trials."""

from .convolutional import (
    CONVOLUTIONAL_CODE_SPECS,
    GENERATOR_POLYNOMIALS,
    ConvolutionalDecodeResult,
    ConvolutionalCodeSpec,
    convolutional_encode,
    decode_viterbi,
    encode_convolutional,
    viterbi_decode,
)
from .concatenated import (
    CONCAT_CODED_BITS,
    CONCAT_FEC_NAME,
    CONCAT_INNER_FEC,
    CONCAT_OUTER_FEC,
    CONCAT_PAYLOAD_BITS,
    CONCAT_RS_CODEWORD_BITS,
    ConcatenatedDecodeResult,
    decode_concatenated,
    encode_concatenated,
)
from .ldpc_decoder import (
    IEEE_REFERENCE_ID,
    LDPC_CONFIGS,
    LDPC_CONFIG_NAMES,
    LDPC_DECODER_ALGORITHM,
    LDPC_TYPE_NAMES,
    LDPCConfig,
    LDPCDecodeResult,
    LDPCFrameDecodeResult,
    build_parity_check_matrix,
    decode_ldpc,
    decode_ldpc_frame,
    encode_ldpc,
    encode_ldpc_frame,
    get_ldpc_config,
)
from .reed_solomon import RS_CODE_SPECS, ReedSolomonCodeSpec, ReedSolomonDecodeResult, rs_decode, rs_encode
from .trial_engine import TrialResult, TrialSearchResult, run_fec_trials

__all__ = [
    "CONVOLUTIONAL_CODE_SPECS",
    "CONCAT_CODED_BITS",
    "CONCAT_FEC_NAME",
    "CONCAT_INNER_FEC",
    "CONCAT_OUTER_FEC",
    "CONCAT_PAYLOAD_BITS",
    "CONCAT_RS_CODEWORD_BITS",
    "GENERATOR_POLYNOMIALS",
    "IEEE_REFERENCE_ID",
    "LDPC_CONFIGS",
    "LDPC_CONFIG_NAMES",
    "LDPC_DECODER_ALGORITHM",
    "LDPC_TYPE_NAMES",
    "LDPCConfig",
    "LDPCDecodeResult",
    "LDPCFrameDecodeResult",
    "RS_CODE_SPECS",
    "ConcatenatedDecodeResult",
    "ConvolutionalDecodeResult",
    "ConvolutionalCodeSpec",
    "ReedSolomonCodeSpec",
    "ReedSolomonDecodeResult",
    "TrialResult",
    "TrialSearchResult",
    "convolutional_encode",
    "build_parity_check_matrix",
    "decode_ldpc",
    "decode_ldpc_frame",
    "decode_concatenated",
    "decode_viterbi",
    "encode_concatenated",
    "encode_ldpc",
    "encode_ldpc_frame",
    "get_ldpc_config",
    "encode_convolutional",
    "rs_decode",
    "rs_encode",
    "run_fec_trials",
    "viterbi_decode",
]
